export const actions = {
  FETCH_REPO_MAIN: 'FETCH_REPO_MAIN',
  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
  FETCH_DATA_SAGA: 'FETCH_DATA_SAGA',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILED: 'FETCH_DATA_FAILED',
  FETCH_MORE_DATA: 'FETCH_MORE_DATA',
  FETCH_MORE_DATA_SUCCESS: 'FETCH_MORE_DATA_SUCCESS',
  FETCH_LOADING: 'FETCH_LOADING',
  FETCH_MORE_LOADING: 'FETCH_MORE_LOADING',
};
