export const actions = {
    FETCH_DATA_REQUEST: "FETCH_DATA_REQUEST",
    FETCH_DATA_SAGA: "FETCH_DATA_SAGA",
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILED: 'FETCH_DATA_FAILED',
};